apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-btdt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-btdt
    app.kubernetes.io/part-of: test-annotations-app-bnbx
  name: test-annotations-btdt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-btdt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-btdt
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-zunq-tenant/test-annotations-app-bnbx/test-annotations-btdt@sha256:40e28bf9144876b7322a9fe3d7ff7e9903950b3d32f120775b109a0396076bcf
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
